### ISSUE TITLE
Move calculation to BeforeRender()

### ISSUE THREAD

**Issue by kC0pter** [petikk/ZyHelperFix#1]
Some of my mates have issues of lagging HUD while using the helper.
I suggest moving the whole calculation of the clipboard BitArray to the BeforeRender() function
instead of having it in the InGameTopPainter.
That should reduce visual lag.

**Comment by petikk** [comment]
Actually didn't know that's a thing. 
Do you have an example plugin that uses this function?

I'm on vacation and will be back soon.

**Comment by petikk** [comment]
Actually done. Performance really imporved, thanks.
